// 实现错题的列表、详情、创建、编辑与删除业务。
import { Prisma } from '@prisma/client';
import { prisma } from '../../config/prisma';
import { cleanMarkdown } from '../../config/markdown';
import { WrongInput, WrongPatch, WrongQuery } from './wrong.dto';
import { ApiError, assertRecordExists, handlePrismaNotFound } from '../../lib/errors';
import { cleanupDeletedEntityImages } from '../../lib/image-cleanup';
const select = { id: true, problemId: true, title: true, category: true, difficulty: true, review: true, solutionLinks: true, createdAt: true, updatedAt: true } as const;
const listSelect = { ...select, _count: { select: { notes: true } } } as const;
const ensureProblem = async (userId: string, problemId: string | null | undefined): Promise<void> => { if (problemId !== undefined && problemId !== null) assertRecordExists(await prisma.problem.findFirst({ where: { id: problemId, userId }, select: { id: true } }), 'PROBLEM_NOT_FOUND', 'Problem does not exist'); };
export const listWrongs = async (userId: string, query: WrongQuery) => { const where: Prisma.WrongWhereInput = { userId, ...(query.keyword ? { title: { contains: query.keyword, mode: 'insensitive' } } : {}), ...(query.category ? { category: query.category } : {}), ...(query.difficulty ? { difficulty: query.difficulty } : {}) }; const [total, rows] = await prisma.$transaction([prisma.wrong.count({ where }), prisma.wrong.findMany({ where, select: listSelect, orderBy: [{ updatedAt: 'desc' }, { createdAt: 'desc' }], skip: (query.page - 1) * query.pageSize, take: query.pageSize })]); const data = rows.map(({ _count, ...wrong }) => ({ ...wrong, noteCount: _count.notes })); return { data, pagination: { page: query.page, pageSize: query.pageSize, total, totalPages: Math.ceil(total / query.pageSize) } }; };
export const getWrong = async (userId: string, id: string) => { const data = await prisma.wrong.findFirst({ where: { id, userId }, select }); return { data: assertRecordExists(data, 'WRONG_NOT_FOUND', 'Wrong does not exist') }; };
export const createWrong = async (userId: string, input: WrongInput) => { await ensureProblem(userId, input.problemId); return { data: await prisma.wrong.create({ data: { userId, problemId: input.problemId ?? null, title: input.title.trim(), category: input.category?.trim() || null, difficulty: input.difficulty, review: input.review === undefined || input.review === null ? null : cleanMarkdown(input.review), solutionLinks: input.solutionLinks as unknown as Prisma.InputJsonValue }, select }) }; };
export const updateWrong = async (userId: string, id: string, input: WrongPatch) => { await ensureProblem(userId, input.problemId); try { return { data: await prisma.wrong.update({ where: { id, userId }, data: { ...(input.problemId === undefined ? {} : { problemId: input.problemId }), ...(input.title === undefined ? {} : { title: input.title.trim() }), ...(input.category === undefined ? {} : { category: input.category?.trim() || null }), ...(input.difficulty === undefined ? {} : { difficulty: input.difficulty }), ...(input.review === undefined ? {} : { review: input.review === null ? null : cleanMarkdown(input.review) }), ...(input.solutionLinks === undefined ? {} : { solutionLinks: input.solutionLinks as unknown as Prisma.InputJsonValue }) }, select }) }; } catch (error: unknown) { return handlePrismaNotFound(error, 'WRONG_NOT_FOUND', 'Wrong does not exist'); } };
export const deleteWrong = async (userId: string, id: string): Promise<void> => { const existing = assertRecordExists(await prisma.wrong.findFirst({ where: { id, userId }, select: { review: true } }), 'WRONG_NOT_FOUND', 'Wrong does not exist'); try { await prisma.wrong.delete({ where: { id, userId } }); } catch (error: unknown) { handlePrismaNotFound(error, 'WRONG_NOT_FOUND', 'Wrong does not exist'); } await cleanupDeletedEntityImages(existing.review); };
