// 定义错题 CRUD 的请求参数、查询参数与校验。
import { Difficulty } from '@prisma/client';

export interface SolutionLink { name: string; url: string }
export interface WrongInput { problemId?: string | null; title: string; category?: string | null; difficulty: Difficulty; review?: string | null; solutionLinks: SolutionLink[] }
export interface WrongPatch { problemId?: string | null; title?: string; category?: string | null; difficulty?: Difficulty; review?: string | null; solutionLinks?: SolutionLink[] }
export interface WrongQuery { page: number; pageSize: number; keyword?: string; category?: string; difficulty?: Difficulty }
const difficulties = new Set<Difficulty>(['EASY', 'MEDIUM', 'HARD']);
const validLinks = (value: unknown): value is SolutionLink[] => Array.isArray(value) && value.length <= 20 && value.every((link) => { if (!link || typeof link !== 'object') return false; const item = link as { name?: unknown; url?: unknown }; return typeof item.name === 'string' && item.name.trim().length > 0 && item.name.trim().length <= 100 && typeof item.url === 'string' && /^https?:\/\//.test(item.url); });
const validOptionalText = (value: unknown, max: number): boolean => value === undefined || value === null || (typeof value === 'string' && value.length <= max);
export const isWrongInput = (value: unknown): value is WrongInput => { if (!value || typeof value !== 'object') return false; const item = value as Partial<WrongInput>; return (item.problemId === undefined || item.problemId === null || typeof item.problemId === 'string') && typeof item.title === 'string' && item.title.trim().length > 0 && item.title.trim().length <= 255 && validOptionalText(item.category, 100) && typeof item.difficulty === 'string' && difficulties.has(item.difficulty as Difficulty) && validOptionalText(item.review, 100000) && validLinks(item.solutionLinks); };
export const isWrongPatch = (value: unknown): value is WrongPatch => { if (!value || typeof value !== 'object') return false; const item = value as WrongPatch; return Object.keys(item).length > 0 && (item.problemId === undefined || item.problemId === null || typeof item.problemId === 'string') && (item.title === undefined || (typeof item.title === 'string' && item.title.trim().length > 0 && item.title.trim().length <= 255)) && validOptionalText(item.category, 100) && (item.difficulty === undefined || (typeof item.difficulty === 'string' && difficulties.has(item.difficulty as Difficulty))) && validOptionalText(item.review, 100000) && (item.solutionLinks === undefined || validLinks(item.solutionLinks)); };
export const parseWrongQuery = (query: Record<string, unknown>): WrongQuery => { const page = Number(query.page) || 1; const pageSize = Number(query.pageSize) || 20; if (!Number.isInteger(page) || page < 1 || !Number.isInteger(pageSize) || pageSize < 1 || pageSize > 100) throw new Error('INVALID_QUERY'); const difficulty = query.difficulty === undefined ? undefined : difficulties.has(query.difficulty as Difficulty) ? query.difficulty as Difficulty : undefined; if (query.difficulty !== undefined && !difficulty) throw new Error('INVALID_QUERY'); return { page, pageSize, keyword: typeof query.keyword === 'string' && query.keyword.trim() ? query.keyword.trim() : undefined, category: typeof query.category === 'string' && query.category.trim() ? query.category.trim() : undefined, difficulty }; };
