// 覆盖题解笔记 CRUD、分页搜索与用户数据隔离。
import request from 'supertest';
import { app } from '../src/app';
import { prisma } from '../src/config/prisma';
let sequence = 0;
const user = async (prefix: string): Promise<{ id: string; token: string }> => { sequence += 1; const response = await request(app).post('/api/auth/register').send({ email: `${prefix}${Date.now()}-${sequence}@example.com`, password: 'strong-password' }); return { id: response.body.user.id, token: response.body.token }; };
afterAll(async () => prisma.$disconnect());
describe('note integration', () => {
  it('creates, lists, gets, updates and deletes a note', async () => { const account = await user('note-test-'); const created = await request(app).post('/api/notes').set('Authorization', `Bearer ${account.token}`).send({ title: ' 二分 ', content: '<p>内容</p>', solutionLinks: [{ name: '题解', url: 'https://example.com' }] }); expect(created.status).toBe(201); const id = created.body.data.id; const problem = await prisma.problem.create({ data: { userId: account.id, title: '二分题目', difficulty: 'EASY' } }); const wrong = await prisma.wrong.create({ data: { userId: account.id, title: '二分错题', difficulty: 'EASY' } }); await prisma.problemNote.create({ data: { problemId: problem.id, noteId: id } }); await prisma.wrongNote.create({ data: { wrongId: wrong.id, noteId: id } }); const listed = await request(app).get('/api/notes?keyword=二分').set('Authorization', `Bearer ${account.token}`); expect(listed.body.data).toHaveLength(1); expect(listed.body.data[0]).toMatchObject({ problemCount: 1, wrongCount: 1 }); expect((await request(app).get(`/api/notes/${id}`).set('Authorization', `Bearer ${account.token}`)).body.data.title).toBe('二分'); const updated = await request(app).patch(`/api/notes/${id}`).set('Authorization', `Bearer ${account.token}`).send({ content: '<p>更新</p>' }); expect(updated.body.data.content).toBe('<p>更新</p>'); expect((await request(app).delete(`/api/notes/${id}`).set('Authorization', `Bearer ${account.token}`)).status).toBe(204); expect((await request(app).get(`/api/notes/${id}`).set('Authorization', `Bearer ${account.token}`)).status).toBe(404); });
  it('rejects invalid payload and hides another user note', async () => { const owner = await user('note-test-owner-'); const other = await user('note-test-other-'); const invalid = await request(app).post('/api/notes').set('Authorization', `Bearer ${owner.token}`).send({ title: '', content: '', solutionLinks: [{ name: 'x', url: 'ftp://bad' }] }); expect(invalid.status).toBe(400); const note = await prisma.note.create({ data: { userId: owner.id, title: '私有笔记' } }); expect((await request(app).get(`/api/notes/${note.id}`).set('Authorization', `Bearer ${other.token}`)).status).toBe(404); });
});
