// 覆盖练习记录接口的数据库集成场景。
import request from 'supertest'; import { app } from '../src/app'; import { prisma } from '../src/config/prisma';
const password = 'strong-password'; let sequence = 0;
const user = async (prefix: string): Promise<{ id: string; token: string }> => { sequence += 1; const response = await request(app).post('/api/auth/register').send({ email: `${prefix}${Date.now()}-${sequence}@example.com`, password }); return { id: response.body.user.id as string, token: response.body.token as string }; };
beforeEach(async () => { await prisma.user.deleteMany({ where: { email: { startsWith: 'practice-test-' } } }); }); afterAll(async () => { await prisma.user.deleteMany({ where: { email: { startsWith: 'practice-test-' } } }); await prisma.$disconnect(); });
describe('practice record integration', () => {
  it('records, lists and deletes practice history', async () => { const account = await user('practice-test-'); const problem = await prisma.problem.create({ data: { userId: account.id, title: 'Two Sum', difficulty: 'EASY' } }); const created = await request(app).post(`/api/problems/${problem.id}/practice-records`).set('Authorization', `Bearer ${account.token}`).send({ practicedAt: '2026-09-17', solvedFirstTry: true, remark: '一次通过' }); expect(created.status).toBe(201); const list = await request(app).get(`/api/problems/${problem.id}/practice-records`).set('Authorization', `Bearer ${account.token}`); expect(list.body.pagination.total).toBe(1); const removed = await request(app).delete(`/api/problems/${problem.id}/practice-records/${created.body.data.id}`).set('Authorization', `Bearer ${account.token}`); expect(removed.status).toBe(204); });
  it('enforces validation and user isolation', async () => { const owner = await user('practice-test-owner-'); const other = await user('practice-test-other-'); const problem = await prisma.problem.create({ data: { userId: owner.id, title: '反转链表', difficulty: 'MEDIUM' } }); const invalid = await request(app).post(`/api/problems/${problem.id}/practice-records`).set('Authorization', `Bearer ${owner.token}`).send({ practicedAt: '2026-02-30', solvedFirstTry: true }); expect(invalid.status).toBe(400); expect(invalid.body.code).toBe('INVALID_PRACTICE_RECORD'); const forbidden = await request(app).get(`/api/problems/${problem.id}/practice-records`).set('Authorization', `Bearer ${other.token}`); expect(forbidden.status).toBe(404); expect(forbidden.body.code).toBe('PROBLEM_NOT_FOUND'); });
  it('updates a practice record', async () => { const account = await user('practice-test-update-'); const problem = await prisma.problem.create({ data: { userId: account.id, title: '三数之和', difficulty: 'MEDIUM' } }); const created = await request(app).post(`/api/problems/${problem.id}/practice-records`).set('Authorization', `Bearer ${account.token}`).send({ practicedAt: '2026-09-20', solvedFirstTry: true, remark: '一次通过' }); expect(created.status).toBe(201); const patched = await request(app).patch(`/api/problems/${problem.id}/practice-records/${created.body.data.id}`).set('Authorization', `Bearer ${account.token}`).send({ solvedFirstTry: false, remark: '边界条件遗漏' }); expect(patched.status).toBe(200); expect(patched.body.data.solvedFirstTry).toBe(false); expect(patched.body.data.remark).toBe('边界条件遗漏'); const list = await request(app).get(`/api/problems/${problem.id}/practice-records`).set('Authorization', `Bearer ${account.token}`); expect(list.body.data[0].solvedFirstTry).toBe(false); expect(list.body.data[0].remark).toBe('边界条件遗漏'); });
  it('rejects update with invalid payload', async () => { const account = await user('practice-test-invalid-'); const problem = await prisma.problem.create({ data: { userId: account.id, title: '合并区间', difficulty: 'HARD' } }); const created = await request(app).post(`/api/problems/${problem.id}/practice-records`).set('Authorization', `Bearer ${account.token}`).send({ practicedAt: '2026-09-21', solvedFirstTry: true }); const invalid = await request(app).patch(`/api/problems/${problem.id}/practice-records/${created.body.data.id}`).set('Authorization', `Bearer ${account.token}`).send({ practicedAt: '2026-13-45' }); expect(invalid.status).toBe(400); expect(invalid.body.code).toBe('INVALID_PRACTICE_RECORD'); });
  it('returns 404 when updating a non-existent record', async () => { const account = await user('practice-test-404-'); const problem = await prisma.problem.create({ data: { userId: account.id, title: '爬楼梯', difficulty: 'EASY' } }); const missing = await request(app).patch(`/api/problems/${problem.id}/practice-records/non-existent-id`).set('Authorization', `Bearer ${account.token}`).send({ solvedFirstTry: false }); expect(missing.status).toBe(404); expect(missing.body.code).toBe('PRACTICE_RECORD_NOT_FOUND'); });
});
