// 覆盖学习进度 CRUD、校验、搜索与用户数据隔离。
import request from 'supertest';
import { app } from '../src/app';
import { prisma } from '../src/config/prisma';
let sequence = 0;
const user = async (prefix: string): Promise<{ id: string; token: string }> => { sequence += 1; const response = await request(app).post('/api/auth/register').send({ email: `${prefix}${Date.now()}-${sequence}@example.com`, password: 'strong-password' }); return { id: response.body.user.id, token: response.body.token }; };
afterAll(async () => prisma.$disconnect());
describe('progress integration', () => {
  it('creates, lists, gets, updates and deletes a progress', async () => { const account = await user('progress-test-'); const created = await request(app).post('/api/progresses').set('Authorization', `Bearer ${account.token}`).send({ title: ' 动态规划 ', progress: 60, progressDate: '2026-09-18', description: '基础学习' }); expect(created.status).toBe(201); const id = created.body.data.id; const list = await request(app).get('/api/progresses?keyword=动态规划').set('Authorization', `Bearer ${account.token}`); expect(list.status).toBe(200); expect(list.body.data).toHaveLength(1); expect((await request(app).get(`/api/progresses/${id}`).set('Authorization', `Bearer ${account.token}`)).body.data.title).toBe('动态规划'); const updated = await request(app).patch(`/api/progresses/${id}`).set('Authorization', `Bearer ${account.token}`).send({ progress: 100, description: null }); expect(updated.body.data.progress).toBe(100); expect((await request(app).delete(`/api/progresses/${id}`).set('Authorization', `Bearer ${account.token}`)).status).toBe(204); expect((await request(app).get(`/api/progresses/${id}`).set('Authorization', `Bearer ${account.token}`)).status).toBe(404); });
  it('rejects invalid values and hides another user progress', async () => { const owner = await user('progress-owner-'); const other = await user('progress-other-'); expect((await request(app).post('/api/progresses').set('Authorization', `Bearer ${owner.token}`).send({ title: '越界', progress: 101, progressDate: '2026-09-18' })).body.code).toBe('INVALID_PROGRESS_INPUT'); const progress = await prisma.progress.create({ data: { userId: owner.id, title: '私有进度', progress: 10, progressDate: new Date('2026-09-18T00:00:00.000Z') } }); expect((await request(app).get(`/api/progresses/${progress.id}`).set('Authorization', `Bearer ${other.token}`)).status).toBe(404); });
});
