// 覆盖待办 CRUD、筛选、逾期判断与用户数据隔离。
import request from 'supertest';
import { app } from '../src/app';
import { prisma } from '../src/config/prisma';
let sequence = 0;
const user = async (prefix: string): Promise<{ id: string; token: string }> => { sequence += 1; const response = await request(app).post('/api/auth/register').send({ email: `${prefix}${Date.now()}-${sequence}@example.com`, password: 'strong-password' }); return { id: response.body.user.id, token: response.body.token }; };
afterAll(async () => prisma.$disconnect());
describe('todo integration', () => {
  it('creates, lists, gets, updates and deletes a todo', async () => { const account = await user('todo-test-'); const created = await request(app).post('/api/todos').set('Authorization', `Bearer ${account.token}`).send({ title: ' 复习二叉树 ', dueDate: '2026-09-20', priority: 'P0', remark: '完成 10 道题' }); expect(created.status).toBe(201); const id = created.body.data.id; const list = await request(app).get('/api/todos?priority=P0&keyword=二叉树').set('Authorization', `Bearer ${account.token}`); expect(list.status).toBe(200); expect(list.body.data).toHaveLength(1); expect((await request(app).get(`/api/todos/${id}`).set('Authorization', `Bearer ${account.token}`)).body.data.title).toBe('复习二叉树'); const updated = await request(app).patch(`/api/todos/${id}`).set('Authorization', `Bearer ${account.token}`).send({ status: 'COMPLETED' }); expect(updated.body.data.status).toBe('COMPLETED'); expect((await request(app).delete(`/api/todos/${id}`).set('Authorization', `Bearer ${account.token}`)).status).toBe(204); expect((await request(app).get(`/api/todos/${id}`).set('Authorization', `Bearer ${account.token}`)).status).toBe(404); });
  it('rejects invalid payload and hides another user todo', async () => { const owner = await user('todo-owner-'); const other = await user('todo-other-'); expect((await request(app).post('/api/todos').set('Authorization', `Bearer ${owner.token}`).send({ title: '', priority: 'P3' })).status).toBe(400); const todo = await prisma.todo.create({ data: { userId: owner.id, title: '私有待办', priority: 'P1', status: 'TODO' } }); expect((await request(app).get(`/api/todos/${todo.id}`).set('Authorization', `Bearer ${other.token}`)).status).toBe(404); });
  it('marks an unfinished past-due todo as overdue', async () => { const account = await user('todo-overdue-'); const response = await request(app).post('/api/todos').set('Authorization', `Bearer ${account.token}`).send({ title: '逾期待办', dueDate: '2020-01-01', priority: 'P1' }); expect(response.body.data.isOverdue).toBe(true); const list = await request(app).get('/api/todos?overdue=true').set('Authorization', `Bearer ${account.token}`); expect(list.body.data.some((item: { id: string }) => item.id === response.body.data.id)).toBe(true); });
});
