// 实现题目练习记录的查询、新增与删除业务。
import { Prisma } from '@prisma/client';
import { prisma } from '../../config/prisma';
import { CreatePracticeRecordInput, PracticeRecordQuery } from './practice-record.dto';
export class PracticeRecordError extends Error { public constructor(public readonly code: string, message: string, public readonly statusCode: number) { super(message); } }
const dateValue = (value: string): Date => { const date = new Date(`${value}T00:00:00.000Z`); if (Number.isNaN(date.getTime()) || date.toISOString().slice(0, 10) !== value) throw new PracticeRecordError('INVALID_PRACTICE_RECORD', 'Practiced date is invalid', 400); return date; };
const ensureProblem = async (userId: string, problemId: string): Promise<void> => { if (!await prisma.problem.findFirst({ where: { id: problemId, userId }, select: { id: true } })) throw new PracticeRecordError('PROBLEM_NOT_FOUND', 'Problem does not exist', 404); };
export const listPracticeRecords = async (userId: string, problemId: string, query: PracticeRecordQuery) => { await ensureProblem(userId, problemId); const where = { userId, problemId }; const [total, data] = await prisma.$transaction([prisma.practiceRecord.count({ where }), prisma.practiceRecord.findMany({ where, orderBy: [{ practicedAt: 'desc' }, { createdAt: 'desc' }], skip: (query.page - 1) * query.pageSize, take: query.pageSize, select: { id: true, practicedAt: true, solvedFirstTry: true, remark: true, createdAt: true } })]); return { data, pagination: { page: query.page, pageSize: query.pageSize, total, totalPages: Math.ceil(total / query.pageSize) } }; };
export const createPracticeRecord = async (userId: string, problemId: string, input: CreatePracticeRecordInput) => { await ensureProblem(userId, problemId); const record = await prisma.practiceRecord.create({ data: { userId, problemId, practicedAt: dateValue(input.practicedAt), solvedFirstTry: input.solvedFirstTry, remark: input.remark ?? null }, select: { id: true, problemId: true, practicedAt: true, solvedFirstTry: true, remark: true, createdAt: true } }); return { data: record }; };
export const deletePracticeRecord = async (userId: string, problemId: string, recordId: string): Promise<void> => { try { await prisma.practiceRecord.delete({ where: { id: recordId, userId, problemId } }); } catch (error: unknown) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2025') throw new PracticeRecordError('PRACTICE_RECORD_NOT_FOUND', 'Practice record does not exist', 404); throw error; } };
