import { flushPromises, mount } from '@vue/test-utils';
import { createPinia } from 'pinia';
import { describe, expect, it, vi } from 'vitest';
import { api } from '../src/api';
import WrongList from '../src/views/WrongList.vue';
import NoteList from '../src/views/NoteList.vue';
import { createMemoryHistory, createRouter } from 'vue-router';
vi.mock('../src/api', () => ({ api: { get: vi.fn() } }));
const testRouter = () => createRouter({ history: createMemoryHistory(), routes: [{ path: '/wrongs/:wrongId', component: {} }, { path: '/notes/:noteId', component: {} }] });
describe('list views', () => { it('renders wrong empty state', async () => { vi.mocked(api.get).mockResolvedValueOnce({ data: { data: [], pagination: { page: 1, pageSize: 9, total: 0, totalPages: 0 } } }); const wrapper = mount(WrongList, { global: { plugins: [createPinia(), testRouter()] } }); await flushPromises(); expect(wrapper.text()).toContain('还没有错题'); }); it('renders note rows', async () => { vi.mocked(api.get).mockResolvedValueOnce({ data: { data: [{ id: 'n1', title: '二分笔记', content: '<p>边界</p>', problemCount: 2, wrongCount: 1, updatedAt: '2026-09-20T08:00:00.000Z' }], pagination: { page: 1, pageSize: 9, total: 1, totalPages: 1 } } }); const wrapper = mount(NoteList, { global: { plugins: [createPinia(), testRouter()] } }); await flushPromises(); expect(wrapper.text()).toContain('二分笔记'); expect(wrapper.text()).toContain('边界'); }); });
