// 实现题解笔记的查询、创建、编辑与删除业务。
import { Prisma } from '@prisma/client';
import { prisma } from '../../config/prisma';
import { cleanMarkdown } from '../../config/markdown';
import { NoteInput, NotePatch, NoteQuery } from './note.dto';
import { ApiError, assertRecordExists, handlePrismaNotFound } from '../../lib/errors';
import { cleanupDeletedEntityImages } from '../../lib/image-cleanup';
const select = { id: true, title: true, content: true, solutionLinks: true, createdAt: true, updatedAt: true } as const;
const listSelect = { ...select, _count: { select: { problems: true, wrongs: true } } } as const;
const convert = (note: Prisma.NoteGetPayload<{ select: typeof select }>) => note;
export const listNotes = async (userId: string, query: NoteQuery) => { const where = { userId, ...(query.keyword ? { title: { contains: query.keyword, mode: 'insensitive' as const } } : {}) }; const [total, rows] = await prisma.$transaction([prisma.note.count({ where }), prisma.note.findMany({ where, select: listSelect, orderBy: { updatedAt: 'desc' }, skip: (query.page - 1) * query.pageSize, take: query.pageSize })]); const data = rows.map(({ _count, ...note }) => ({ ...note, problemCount: _count.problems, wrongCount: _count.wrongs })); return { data, pagination: { page: query.page, pageSize: query.pageSize, total, totalPages: Math.ceil(total / query.pageSize) } }; };
export const getNote = async (userId: string, id: string) => { const row = await prisma.note.findFirst({ where: { id, userId }, select }); return { data: convert(assertRecordExists(row, 'NOTE_NOT_FOUND', 'Note does not exist')) }; };
export const createNote = async (userId: string, input: NoteInput) => ({ data: convert(await prisma.note.create({ data: { userId, title: input.title.trim(), content: cleanMarkdown(input.content), solutionLinks: input.solutionLinks as unknown as Prisma.InputJsonValue }, select })) });
export const updateNote = async (userId: string, id: string, input: NotePatch) => { try { return { data: convert(await prisma.note.update({ where: { id, userId }, data: { ...(input.title === undefined ? {} : { title: input.title.trim() }), ...(input.content === undefined ? {} : { content: cleanMarkdown(input.content) }), ...(input.solutionLinks === undefined ? {} : { solutionLinks: input.solutionLinks as unknown as Prisma.InputJsonValue }) }, select })) }; } catch (error: unknown) { return handlePrismaNotFound(error, 'NOTE_NOT_FOUND', 'Note does not exist'); } };
export const deleteNote = async (userId: string, id: string): Promise<void> => { const existing = assertRecordExists(await prisma.note.findFirst({ where: { id, userId }, select: { content: true } }), 'NOTE_NOT_FOUND', 'Note does not exist'); try { await prisma.note.delete({ where: { id, userId } }); } catch (error: unknown) { handlePrismaNotFound(error, 'NOTE_NOT_FOUND', 'Note does not exist'); } await cleanupDeletedEntityImages(existing.content); };
const wrongSelect = { id: true, title: true, category: true, difficulty: true, createdAt: true, updatedAt: true } as const;
export const getNoteWrongs = async (userId: string, noteId: string) => { const note = await prisma.note.findFirst({ where: { id: noteId, userId }, select: { id: true } }); assertRecordExists(note, 'NOTE_NOT_FOUND', 'Note does not exist'); const wrongs = await prisma.wrong.findMany({ where: { userId, notes: { some: { noteId } } }, select: wrongSelect, orderBy: { updatedAt: 'desc' } }); return { data: { noteId, wrongs } }; };
