// 实现学习进度的查询、创建、编辑与删除业务。
import { Prisma } from '@prisma/client';
import { prisma } from '../../config/prisma';
import { ProgressInput, ProgressPatch, ProgressQuery } from './progress.dto';
import { assertRecordExists, handlePrismaNotFound } from '../../lib/errors';
import { cleanupDeletedEntityImages } from '../../lib/image-cleanup';
const select = { id: true, title: true, progress: true, progressDate: true, description: true, createdAt: true, updatedAt: true } as const;
const dateValue = (value: string): Date => new Date(`${value}T00:00:00.000Z`);
export const listProgresses = async (userId: string, query: ProgressQuery) => { const where: Prisma.ProgressWhereInput = { userId, ...(query.keyword ? { OR: [{ title: { contains: query.keyword, mode: 'insensitive' } }, { description: { contains: query.keyword, mode: 'insensitive' } }] } : {}) }; const [total, rows] = await prisma.$transaction([prisma.progress.count({ where }), prisma.progress.findMany({ where, select, orderBy: [{ progressDate: 'desc' }, { createdAt: 'desc' }], skip: (query.page - 1) * query.pageSize, take: query.pageSize })]); return { data: rows, pagination: { page: query.page, pageSize: query.pageSize, total, totalPages: Math.ceil(total / query.pageSize) } }; };
export const getProgress = async (userId: string, id: string) => { const row = await prisma.progress.findFirst({ where: { id, userId }, select }); return { data: assertRecordExists(row, 'PROGRESS_NOT_FOUND', 'Progress does not exist') }; };
export const createProgress = async (userId: string, input: ProgressInput) => ({ data: await prisma.progress.create({ data: { userId, title: input.title.trim(), progress: input.progress, progressDate: dateValue(input.progressDate), description: input.description ?? null }, select }) });
export const updateProgress = async (userId: string, id: string, input: ProgressPatch) => { try { return { data: await prisma.progress.update({ where: { id, userId }, data: { ...(input.title === undefined ? {} : { title: input.title.trim() }), ...(input.progress === undefined ? {} : { progress: input.progress }), ...(input.progressDate === undefined ? {} : { progressDate: dateValue(input.progressDate) }), ...(input.description === undefined ? {} : { description: input.description }) }, select }) }; } catch (error: unknown) { return handlePrismaNotFound(error, 'PROGRESS_NOT_FOUND', 'Progress does not exist'); } };
export const deleteProgress = async (userId: string, id: string): Promise<void> => { const existing = assertRecordExists(await prisma.progress.findFirst({ where: { id, userId }, select: { description: true } }), 'PROGRESS_NOT_FOUND', 'Progress does not exist'); try { await prisma.progress.delete({ where: { id, userId } }); } catch (error: unknown) { handlePrismaNotFound(error, 'PROGRESS_NOT_FOUND', 'Progress does not exist'); } await cleanupDeletedEntityImages(existing.description); };
