<!-- Category board for the practice workflow with category management. -->
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { useCategoryStore } from '../stores/category';
const store = useCategoryStore();
const formOpen = ref(false); const editingId = ref<string | null>(null); const name = ref('');
function openCreate(): void { editingId.value = null; name.value = ''; formOpen.value = true; }
function openEdit(id: string, current: string): void { editingId.value = id; name.value = current; formOpen.value = true; }
async function save(): Promise<void> { const trimmed = name.value.trim(); if (!trimmed) return; const result = editingId.value ? await store.rename(editingId.value, trimmed) : await store.create(trimmed); if (result) formOpen.value = false; }
async function remove(id: string, label: string): Promise<void> { if (window.confirm(`确定删除分类“${label}”吗？其题目关联将一并解除。`)) await store.remove(id); }
onMounted(() => { void store.fetch(); });
</script>
<template><section class="p-5 md:p-8"><div class="mb-8 flex flex-wrap items-end justify-between gap-3"><div><p class="text-xs uppercase tracking-[0.2em] text-[var(--color-accent)]">Practice board</p><h2 class="mt-2 text-2xl font-semibold">按分类开始练习</h2></div><button class="bg-[var(--color-accent)] px-4 py-2 font-semibold text-white" @click="openCreate">新建分类</button></div><p v-if="store.loading" role="status">正在加载分类…</p><p v-else-if="store.error" role="alert">{{ store.error }} <button class="underline" @click="store.fetch">重试</button></p><p v-else-if="!store.items.length">还没有分类，先创建一个分类吧。</p><div v-else class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><article v-for="item in store.items" :key="item.id" class="border border-[var(--color-border)] p-4 hover:border-[var(--color-accent)]"><div class="flex items-start justify-between gap-2"><RouterLink :to="`/categories/${item.id}/problems`" class="min-w-0"><h3 class="truncate font-semibold">{{ item.name }}</h3><p class="mt-3 text-sm text-[var(--color-accent)]">{{ item.problemCount }} 道题目</p></RouterLink><div class="flex shrink-0 gap-2 text-sm"><button class="underline" @click="openEdit(item.id, item.name)">重命名</button><button :disabled="store.deleting" class="text-red-700 underline" @click="remove(item.id, item.name)">删除</button></div></div></article></div><p v-if="store.deleteError" role="alert" class="mt-3 text-sm text-red-700">{{ store.deleteError }}</p>
<div v-if="formOpen" class="fixed inset-0 grid place-items-center bg-black/30 p-4"><form class="w-full max-w-md space-y-4 bg-[var(--color-bg)] p-5" @submit.prevent="save"><h3 class="text-xl font-semibold">{{ editingId ? '重命名分类' : '新建分类' }}</h3><label class="block">分类名称<input v-model="name" aria-label="分类名称" required maxlength="100" class="mt-1 w-full border px-3 py-2" /></label><p v-if="store.saveError" role="alert" class="text-sm text-red-700">{{ store.saveError }}</p><div class="flex justify-end gap-3"><button type="button" class="border px-4 py-2" @click="formOpen = false">取消</button><button :disabled="store.saving" class="bg-[var(--color-accent)] px-4 py-2 text-white" type="submit">{{ store.saving ? '保存中…' : '保存' }}</button></div></form></div></section></template>
