<!-- Note detail page with edit/delete and linked wrongs. -->
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { useNoteStore } from '../stores/note'; import RichTextEditor from '../components/editor/RichTextEditor.vue'; import MarkdownRenderer from '../components/editor/MarkdownRenderer.vue';
const route = useRoute(); const router = useRouter(); const store = useNoteStore(); const id = String(route.params.noteId);
const editing = ref(false); const form = reactive({ title: '', content: '' });
function edit(): void { if (!store.note) return; form.title = store.note.title; form.content = store.note.content ?? ''; editing.value = true; }
async function save(): Promise<void> { if (!form.title.trim()) return; if (await store.update(id, { title: form.title, content: form.content })) editing.value = false; }
async function remove(): Promise<void> { if (window.confirm('确定删除这篇笔记吗？') && await store.remove(id)) await router.push('/notes'); }
onMounted(() => store.fetch(id));
</script>
<template><main class="grid gap-4 p-6 md:grid-cols-[1fr_280px]"><article><div class="flex flex-wrap items-start justify-between gap-3"><h1 class="text-2xl">{{ store.note?.title ?? '题解笔记' }}</h1><div class="flex gap-3 text-sm"><button class="underline" @click="edit">编辑</button><button :disabled="store.deleting" class="text-red-700 underline" @click="remove">删除</button></div></div><form v-if="editing" class="mt-4 space-y-3 border p-4" @submit.prevent="save"><label class="block">标题<input v-model="form.title" aria-label="笔记标题" required maxlength="200" class="mt-1 w-full border px-3 py-2" /></label><label class="block">内容<RichTextEditor v-model="form.content" class="mt-1" /></label><p v-if="store.saveError" role="alert" class="text-sm text-red-700">{{ store.saveError }}</p><div class="flex gap-3"><button :disabled="store.saving" class="bg-[var(--color-accent)] px-4 py-2 text-white" type="submit">{{ store.saving ? '保存中…' : '保存' }}</button><button type="button" class="border px-4 py-2" @click="editing = false">取消</button></div></form><MarkdownRenderer v-else-if="store.note?.content" :content="store.note.content" class="mt-4" /><p v-else class="mt-4 text-sm opacity-60">暂无内容。</p><p v-if="store.deleteError" role="alert" class="mt-3 text-sm text-red-700">{{ store.deleteError }}</p></article><aside class="border p-4"><h2>关联错题</h2><ul class="mt-2 space-y-2"><li v-for="wrong in store.wrongs" :key="wrong.id"><RouterLink :to="`/wrongs/${wrong.id}`">{{ wrong.title }}</RouterLink></li><li v-if="!store.wrongs.length">暂无关联错题</li></ul></aside></main></template>
