<!-- Paginated solution-note list with keyword search and relation counts. -->
<script setup lang="ts">
import { onMounted } from 'vue';
import { useNoteListStore } from '../stores/noteList';
import PaginationNav from '../components/PaginationNav.vue';
const store = useNoteListStore();
onMounted(() => store.fetch());
function summary(content: string | null): string { return (content ?? '').replace(/<[^>]*>/g, '').replace(/\s+/g, ' ').trim().slice(0, 120) || '暂无内容摘要'; }
</script>
<template><section class="mx-auto max-w-5xl p-5 md:p-10"><header class="border-b border-[var(--color-border)] pb-6"><p class="text-xs uppercase tracking-[0.18em] text-[var(--color-accent)]">Reference shelf / 02</p><h2 class="mt-2 text-3xl font-semibold tracking-tight">题解笔记</h2><p class="mt-2 max-w-xl text-sm opacity-70">把解决问题的方法留下，让下一次检索比记忆更可靠。</p></header><form class="mt-6 flex gap-3 border border-[var(--color-border)] bg-white/30 p-4" @submit.prevent="store.search"><label class="sr-only" for="note-keyword">搜索笔记</label><input id="note-keyword" v-model="store.keyword" class="min-w-0 flex-1 border border-[var(--color-border)] bg-transparent px-3 py-2" placeholder="搜索笔记标题" /><button class="bg-[var(--color-accent)] px-4 py-2 font-semibold text-white" type="submit">搜索</button></form><p v-if="store.loading" class="py-12 text-center text-sm opacity-70">正在翻阅笔记…</p><div v-else-if="store.error" class="mt-6 border border-red-300 p-5 text-sm text-red-700">{{ store.error }}<button class="ml-3 underline" @click="store.fetch">重试</button></div><div v-else-if="!store.items.length" class="mt-6 border border-dashed border-[var(--color-border)] p-10 text-center"><p class="font-semibold">还没有找到题解笔记</p><p class="mt-2 text-sm opacity-70">换个关键词试试。</p></div><div v-else class="mt-6 grid gap-3"><RouterLink v-for="note in store.items" :key="note.id" :to="`/notes/${note.id}`" class="border border-[var(--color-border)] p-4 transition-colors hover:border-[var(--color-accent)] hover:bg-[var(--color-accent-light)]/40"><h3 class="font-semibold">{{ note.title }}</h3><p class="mt-2 text-sm leading-6 opacity-70">{{ summary(note.content) }}</p><div class="mt-4 flex flex-wrap gap-2 text-xs opacity-70"><span>{{ note.problemCount }} 道关联题目</span><span>{{ note.wrongCount }} 道关联错题</span></div></RouterLink></div><PaginationNav class="mt-6" :page="store.pagination.page" :total-pages="store.pagination.totalPages" @page="store.setPage" /></section></template>
