<!-- Filtered problem list for a category. -->
<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { useProblemListStore } from '../stores/problemList'; import type { Difficulty } from '../types';
const route = useRoute(); const router = useRouter(); const store = useProblemListStore(); const categoryId = String(route.params.categoryId);
const formOpen = ref(false); const form = ref({ title: '', difficulty: 'EASY' as Difficulty, internalNote: '' });
function openCreate(): void { form.value = { title: '', difficulty: 'EASY', internalNote: '' }; formOpen.value = true; }
async function save(): Promise<void> { if (!form.value.title.trim()) return; const ok = await store.create({ ...form.value, categoryIds: [categoryId] }); if (ok) formOpen.value = false; }
onMounted(() => { void store.fetch(categoryId); });
const difficultyLabel: Record<Difficulty, string> = { EASY: '简单', MEDIUM: '中等', HARD: '困难' };
</script>
<template><section class="p-5 md:p-8"><div class="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p class="text-xs uppercase tracking-[0.2em] text-[var(--color-accent)]">Problem list</p><h2 class="mt-2 text-2xl font-semibold">题目列表</h2></div><div class="flex w-full flex-wrap gap-2 sm:w-auto"><button class="bg-[var(--color-accent)] px-4 py-2 font-semibold text-white" @click="openCreate">新增题目</button><input v-model="store.keyword" class="min-w-0 border border-[var(--color-border)] bg-transparent px-3 py-2 text-sm" placeholder="搜索题目" @keyup.enter="store.search"><select v-model="store.difficulty" aria-label="难度筛选" class="border border-[var(--color-border)] bg-transparent px-3 py-2 text-sm" @change="store.search()"><option value="">全部难度</option><option value="EASY">简单</option><option value="MEDIUM">中等</option><option value="HARD">困难</option></select></div></div><p v-if="store.loading" role="status">正在加载题目…</p><p v-else-if="store.error" role="alert">{{ store.error }} <button class="underline" @click="store.fetch">重试</button></p><p v-else-if="!store.items.length">当前分类还没有题目。</p><div v-else class="space-y-2"><button v-for="item in store.items" :key="item.id" class="flex w-full flex-wrap items-center justify-between gap-3 border border-[var(--color-border)] p-4 text-left hover:border-[var(--color-accent)]" @click="router.push({ path: `/problems/${item.id}`, query: { categoryId } })"><span><strong>{{ item.title }}</strong><span class="ml-3 text-xs text-[var(--color-accent)]">{{ difficultyLabel[item.difficulty] }}</span></span><span class="text-xs text-[var(--color-text)]/70">练习 {{ item.practiceCount }} 次 · 笔记 {{ item.noteCount }} 篇 · 最近 {{ item.lastPracticedAt ?? '暂无' }}</span></button></div><div v-if="store.pagination.totalPages > 1" class="mt-5 flex gap-2"><button v-for="page in store.pagination.totalPages" :key="page" class="border px-3 py-1 text-sm" :class="page === store.pagination.page ? 'border-[var(--color-accent)]' : 'border-[var(--color-border)]'" @click="store.setPage(page)">{{ page }}</button></div>
<div v-if="formOpen" class="fixed inset-0 grid place-items-center bg-black/30 p-4"><form class="w-full max-w-md space-y-4 bg-[var(--color-bg)] p-5" @submit.prevent="save"><h3 class="text-xl font-semibold">新增题目</h3><label class="block">题目标题<input v-model="form.title" aria-label="题目标题" required maxlength="255" class="mt-1 w-full border px-3 py-2" /></label><label class="block">难度<select v-model="form.difficulty" aria-label="题目难度" class="mt-1 w-full border px-3 py-2"><option value="EASY">简单</option><option value="MEDIUM">中等</option><option value="HARD">困难</option></select></label><label class="block">内部笔记（可选）<textarea v-model="form.internalNote" aria-label="内部笔记" rows="4" class="mt-1 w-full border px-3 py-2" /></label><p v-if="store.saveError" role="alert" class="text-sm text-red-700">{{ store.saveError }}</p><div class="flex justify-end gap-3"><button type="button" class="border px-4 py-2" @click="formOpen = false">取消</button><button :disabled="store.saving" class="bg-[var(--color-accent)] px-4 py-2 text-white" type="submit">{{ store.saving ? '保存中…' : '保存' }}</button></div></form></div></section></template>
