<script setup lang="ts">
import { onMounted, reactive } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import PaginationNav from '../components/PaginationNav.vue';
import { useProblemDetailStore } from '../stores/problemDetail';
import { usePracticeRecordStore } from '../stores/practiceRecord';
import type { Difficulty } from '../types';
const route = useRoute(); const router = useRouter(); const id = String(route.params.problemId);
const problem = useProblemDetailStore(); const records = usePracticeRecordStore();
const form = reactive({ practicedAt: new Date().toISOString().slice(0, 10), solvedFirstTry: true, remark: '' });
const difficultyLabel: Record<Difficulty, string> = { EASY: '简单', MEDIUM: '中等', HARD: '困难' };
const submit = async () => { await records.create({ practicedAt: form.practicedAt, solvedFirstTry: form.solvedFirstTry, remark: form.remark || undefined }); form.remark = ''; };
const remove = async (recordId: string) => { if (window.confirm('确认删除这条练习记录吗？')) await records.remove(recordId); };
onMounted(async () => { await problem.fetch(id); if (problem.problem) await records.fetch(id, 1); });
</script>
<template><section class="mx-auto max-w-5xl p-5 md:p-10">
<button class="mb-5 text-sm text-[var(--color-accent)] underline" @click="router.back">← 返回列表</button>
<p v-if="problem.loading" role="status">正在加载题目…</p><p v-else-if="problem.error" role="alert" class="border border-red-300 p-5 text-red-700">{{ problem.error }}</p>
<template v-else-if="problem.problem"><header class="border-b border-[var(--color-border)] pb-6"><div class="flex flex-wrap items-center gap-3"><h2 class="text-3xl font-semibold">{{ problem.problem.title }}</h2><span class="text-sm text-[var(--color-accent)]">{{ difficultyLabel[problem.problem.difficulty] }}</span></div><div class="mt-4 flex flex-wrap gap-2"><span v-for="category in problem.problem.categories" :key="category.id" class="border border-[var(--color-border)] px-2 py-1 text-xs">{{ category.name }}</span><span v-if="!problem.problem.categories.length" class="text-sm opacity-60">未分类</span></div></header>
<div class="mt-6 grid gap-6 lg:grid-cols-[1fr_20rem]"><main class="space-y-6"><article class="border border-[var(--color-border)] p-5"><h3 class="font-semibold">内部笔记</h3><p v-if="!problem.problem.internalNote" class="mt-3 text-sm opacity-60">暂无内部笔记。</p><div v-else class="prose mt-3 max-w-none text-sm leading-6" v-html="problem.problem.internalNote"></div></article><article class="border border-[var(--color-border)] p-5"><h3 class="font-semibold">关联题解笔记</h3><p v-if="!problem.problem.notes.length" class="mt-3 text-sm opacity-60">暂无关联题解笔记。</p><div v-else class="mt-3 flex flex-wrap gap-2"><RouterLink v-for="note in problem.problem.notes" :key="note.id" :to="`/notes/${note.id}`" class="border border-[var(--color-border)] px-3 py-2 text-sm hover:border-[var(--color-accent)]">{{ note.title }}</RouterLink></div></article></main>
<aside><form class="border border-[var(--color-border)] p-5" @submit.prevent="submit"><h3 class="font-semibold">记一次练习</h3><label class="mt-4 block text-sm">日期<input v-model="form.practicedAt" required type="date" class="mt-1 w-full border border-[var(--color-border)] bg-transparent px-3 py-2" /></label><label class="mt-4 flex items-center gap-2 text-sm"><input v-model="form.solvedFirstTry" type="checkbox" />一遍做对</label><label class="mt-4 block text-sm">备注<textarea v-model="form.remark" rows="3" class="mt-1 w-full border border-[var(--color-border)] bg-transparent px-3 py-2" /></label><button :disabled="records.saving" class="mt-4 w-full bg-[var(--color-accent)] px-4 py-2 font-semibold text-white disabled:opacity-50">{{ records.saving ? '保存中…' : '保存练习' }}</button></form></aside></div>
<section class="mt-8"><h3 class="mb-3 font-semibold">练习记录</h3><p v-if="records.loading" role="status">正在加载记录…</p><p v-else-if="records.error" role="alert" class="text-red-700">{{ records.error }}</p><p v-else-if="!records.items.length" class="border border-dashed border-[var(--color-border)] p-6 text-center text-sm opacity-60">还没有练习记录。</p><ul v-else class="space-y-2"><li v-for="record in records.items" :key="record.id" class="flex flex-wrap items-start justify-between gap-3 border border-[var(--color-border)] p-4 text-sm"><div><span>{{ record.practicedAt }}</span><span class="ml-4 text-[var(--color-accent)]">{{ record.solvedFirstTry ? '一遍做对' : '未一遍做对' }}</span><p v-if="record.remark" class="mt-2 opacity-70">{{ record.remark }}</p></div><button class="text-red-700 underline" @click="remove(record.id)">删除</button></li></ul><PaginationNav class="mt-5" :page="records.pagination.page" :total-pages="records.pagination.totalPages" @page="(page) => records.fetch(id, page)" /></section>
</template></section></template>
