<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { useProgressStore, type ProgressInput } from '../stores/progress'; import PaginationNav from '../components/PaginationNav.vue'; import type { Progress } from '../types';
const store = useProgressStore(); const editing = ref<Progress | null>(null); const formOpen = ref(false); const form = ref<ProgressInput>({ title: '', progress: 0, progressDate: new Date().toISOString().slice(0, 10), description: '' });
function openCreate(): void { editing.value = null; form.value = { title: '', progress: 0, progressDate: new Date().toISOString().slice(0, 10), description: '' }; formOpen.value = true; }
async function openEdit(item: Progress): Promise<void> { const current = await store.get(item.id); if (current) { editing.value = current; form.value = { title: current.title, progress: current.progress, progressDate: current.progressDate.slice(0, 10), description: current.description ?? '' }; formOpen.value = true; } }
async function save(): Promise<void> { if (!form.value.title.trim() || store.saving) return; const input = { ...form.value, title: form.value.title.trim(), description: form.value.description || undefined }; const result = editing.value ? await store.update(editing.value.id, input) : await store.create(input); if (result) formOpen.value = false; }
async function remove(item: Progress): Promise<void> { if (window.confirm(`确定删除“${item.title}”吗？`)) await store.remove(item.id); }
onMounted(() => store.fetch());
</script>
<template><section class="mx-auto max-w-5xl p-5 md:p-10"><header class="flex items-start justify-between border-b border-[var(--color-border)] pb-6"><div><p class="text-xs uppercase tracking-[0.18em] text-[var(--color-accent)]">Learning progress</p><h2 class="mt-2 text-3xl font-semibold">学习进度</h2></div><button class="bg-[var(--color-accent)] px-4 py-2 font-semibold text-white" @click="openCreate">新增进度</button></header>
<form class="mt-6 flex gap-3 border p-4" @submit.prevent="store.search"><input v-model="store.keyword" aria-label="关键词" class="min-w-0 flex-1 border px-3 py-2" placeholder="搜索主题或描述" /><button class="bg-[var(--color-accent)] px-4 py-2 text-white">搜索</button></form>
<p v-if="store.loading" role="status" class="py-12 text-center">正在加载进度…</p><div v-else-if="store.listError" role="alert" class="mt-6 border border-red-300 p-5 text-red-700">{{ store.listError }} <button class="underline" @click="store.fetch">重试</button></div><div v-else-if="!store.items.length" class="mt-6 border border-dashed p-10 text-center">还没有学习进度，先记录一条吧。</div><div v-else class="mt-6 grid gap-3"><article v-for="item in store.items" :key="item.id" class="border p-4"><div class="flex items-start justify-between gap-3"><div class="min-w-0 flex-1"><h3 class="font-semibold">{{ item.title }}</h3><p class="mt-1 text-sm opacity-70">{{ item.progressDate }} · {{ item.progress }}%</p><div class="mt-3 h-2 bg-black/10"><div class="h-2 bg-[var(--color-accent)]" :style="{ width: `${item.progress}%` }" role="progressbar" :aria-valuenow="item.progress" aria-valuemin="0" aria-valuemax="100" /></div><p v-if="item.description" class="mt-2 text-sm opacity-80">{{ item.description }}</p></div><div class="flex shrink-0 gap-2 text-sm"><button class="underline" @click="openEdit(item)">编辑</button><button :disabled="store.deleting" class="underline" @click="remove(item)">删除</button></div></div></article></div><p v-if="store.deleteError" role="alert" class="mt-3 text-sm text-red-700">{{ store.deleteError }}</p><PaginationNav class="mt-6" :page="store.pagination.page" :total-pages="store.pagination.totalPages" @page="store.setPage" />
<div v-if="formOpen" class="fixed inset-0 grid place-items-center bg-black/30 p-4"><form class="w-full max-w-lg space-y-4 bg-[var(--color-bg)] p-5" @submit.prevent="save"><h3 class="text-xl font-semibold">{{ editing ? '编辑进度' : '新增进度' }}</h3><label class="block">主题<input v-model="form.title" aria-label="标题" required class="mt-1 w-full border px-3 py-2" /></label><label class="block">进度（0-100）<input v-model.number="form.progress" aria-label="进度" type="number" min="0" max="100" required class="mt-1 w-full border px-3 py-2" /></label><label class="block">日期<input v-model="form.progressDate" aria-label="日期" type="date" required class="mt-1 w-full border px-3 py-2" /></label><label class="block">描述<textarea v-model="form.description" aria-label="描述" class="mt-1 w-full border px-3 py-2" /></label><p v-if="store.saveError" role="alert" class="text-sm text-red-700">{{ store.saveError }}</p><div class="flex justify-end gap-3"><button type="button" class="border px-4 py-2" @click="formOpen = false">取消</button><button :disabled="store.saving" class="bg-[var(--color-accent)] px-4 py-2 text-white">{{ store.saving ? '保存中…' : '保存' }}</button></div></form></div></section></template>
