<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { useTodoStore } from '../stores/todo'; import PaginationNav from '../components/PaginationNav.vue'; import type { Todo, TodoPriority, TodoStatus } from '../types';
const store = useTodoStore(); const editing = ref<Todo | null>(null); const formOpen = ref(false); const form = ref({ title: '', dueDate: '', priority: 'P1' as TodoPriority, status: 'TODO' as TodoStatus, remark: '' });
function openCreate(): void { editing.value = null; form.value = { title: '', dueDate: '', priority: 'P1', status: 'TODO', remark: '' }; formOpen.value = true; }
async function openEdit(todo: Todo): Promise<void> { const current = await store.get(todo.id); if (current) { editing.value = current; form.value = { title: current.title, dueDate: current.dueDate?.slice(0, 10) ?? '', priority: current.priority, status: current.status, remark: current.remark ?? '' }; formOpen.value = true; } }
async function save(): Promise<void> { if (!form.value.title.trim()) return; const input = { ...form.value, title: form.value.title.trim(), dueDate: form.value.dueDate || undefined, remark: form.value.remark || undefined }; const result = editing.value ? await store.update(editing.value.id, input) : await store.create(input); if (result) formOpen.value = false; }
async function remove(todo: Todo): Promise<void> { if (window.confirm(`确定删除“${todo.title}”吗？`)) await store.remove(todo.id); }
onMounted(() => store.fetch());
</script>
<template><section class="mx-auto max-w-5xl p-5 md:p-10"><header class="flex items-start justify-between border-b border-[var(--color-border)] pb-6"><div><p class="text-xs uppercase tracking-[0.18em] text-[var(--color-accent)]">Daily focus</p><h2 class="mt-2 text-3xl font-semibold">待办</h2></div><button class="bg-[var(--color-accent)] px-4 py-2 font-semibold text-white" @click="openCreate">新增待办</button></header>
<form class="mt-6 grid gap-3 border border-[var(--color-border)] bg-white/30 p-4 md:grid-cols-4" @submit.prevent="store.search"><label class="sr-only" for="todo-keyword">关键词</label><input id="todo-keyword" v-model="store.keyword" aria-label="关键词" class="border px-3 py-2" placeholder="搜索标题" /><select v-model="store.status" aria-label="状态" class="border px-3 py-2"><option value="">全部状态</option><option value="TODO">待处理</option><option value="IN_PROGRESS">进行中</option><option value="COMPLETED">已完成</option></select><select v-model="store.priority" aria-label="优先级" class="border px-3 py-2"><option value="">全部优先级</option><option>P0</option><option>P1</option><option>P2</option></select><label class="flex items-center gap-2 px-2"><input v-model="store.overdue" type="checkbox" />仅逾期<button class="ml-auto bg-[var(--color-accent)] px-4 py-2 text-white" type="submit">筛选</button></label></form>
<p v-if="store.loading" class="py-12 text-center">正在加载待办…</p><div v-else-if="store.listError" class="mt-6 border border-red-300 p-5 text-red-700">{{ store.listError }} <button class="underline" @click="store.fetch">重试</button></div><div v-else-if="!store.items.length" class="mt-6 border border-dashed p-10 text-center">还没有待办，先新增一条吧。</div><div v-else class="mt-6 grid gap-3"><article v-for="todo in store.items" :key="todo.id" class="border p-4" :class="[todo.isOverdue ? 'border-red-500 text-red-700' : 'border-[var(--color-border)]', todo.status === 'COMPLETED' ? 'opacity-60 line-through' : '']"><div class="flex items-start justify-between gap-3"><div><h3 class="font-semibold">{{ todo.title }}</h3><p class="mt-2 text-sm">截止：{{ todo.dueDate || '未设置' }} · {{ todo.priority }} · {{ todo.status }}</p><p v-if="todo.remark" class="mt-2 text-sm opacity-80">{{ todo.remark }}</p></div><div class="flex shrink-0 gap-2 text-sm"><button :disabled="store.saving" class="underline" @click="store.toggle(todo)">{{ todo.status === 'COMPLETED' ? '恢复' : '完成' }}</button><button :disabled="store.saving" class="underline" @click="openEdit(todo)">编辑</button><button :disabled="store.deleting" class="underline" @click="remove(todo)">删除</button></div></div></article></div><p v-if="store.deleteError" class="mt-3 text-sm text-red-700">{{ store.deleteError }}</p><PaginationNav class="mt-6" :page="store.pagination.page" :total-pages="store.pagination.totalPages" @page="store.setPage" />
<div v-if="formOpen" class="fixed inset-0 grid place-items-center bg-black/30 p-4"><form class="w-full max-w-lg space-y-4 bg-[var(--color-bg)] p-5" @submit.prevent="save"><h3 class="text-xl font-semibold">{{ editing ? '编辑待办' : '新增待办' }}</h3><label class="block">标题<input v-model="form.title" aria-label="标题" required class="mt-1 w-full border px-3 py-2" /></label><label class="block">截止日期<input v-model="form.dueDate" aria-label="截止日期" type="date" class="mt-1 w-full border px-3 py-2" /></label><label class="block">优先级<select v-model="form.priority" aria-label="优先级" required class="mt-1 w-full border px-3 py-2"><option>P0</option><option>P1</option><option>P2</option></select></label><label class="block">状态<select v-model="form.status" aria-label="状态" class="mt-1 w-full border px-3 py-2"><option value="TODO">待处理</option><option value="IN_PROGRESS">进行中</option><option value="COMPLETED">已完成</option></select></label><label class="block">备注<textarea v-model="form.remark" aria-label="备注" class="mt-1 w-full border px-3 py-2" /></label><p v-if="store.saveError" class="text-sm text-red-700">{{ store.saveError }}</p><div class="flex justify-end gap-3"><button type="button" class="border px-4 py-2" @click="formOpen = false">取消</button><button :disabled="store.saving" class="bg-[var(--color-accent)] px-4 py-2 text-white" type="submit">{{ store.saving ? '保存中…' : '保存' }}</button></div></form></div></section></template>
