<!-- Wrong detail page with edit/delete, solution links, and note association management. -->
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { useWrongListStore } from '../stores/wrongList'; import { useWrongNoteStore } from '../stores/wrongNote'; import { WRONG_CATEGORY_PRESETS } from '../constants'; import type { Difficulty, SolutionLink, Wrong } from '../types'; import RichTextEditor from '../components/editor/RichTextEditor.vue'; import MarkdownRenderer from '../components/editor/MarkdownRenderer.vue';
const route = useRoute(); const router = useRouter(); const wrongs = useWrongListStore(); const store = useWrongNoteStore(); const id = String(route.params.wrongId);
const wrong = ref<Wrong | null>(null); const editing = ref(false); const selected = ref<string[]>([]);
const form = reactive({ title: '', category: '', difficulty: 'EASY' as Difficulty, review: '', links: [] as SolutionLink[] });
const labels: Record<Difficulty, string> = { EASY: '简单', MEDIUM: '中等', HARD: '困难' };
const links = computed<SolutionLink[]>(() => (Array.isArray(wrong.value?.solutionLinks) ? (wrong.value.solutionLinks as SolutionLink[]) : []));
function edit(): void { if (!wrong.value) return; Object.assign(form, { title: wrong.value.title, category: wrong.value.category ?? '', difficulty: wrong.value.difficulty, review: wrong.value.review ?? '', links: links.value.map((link) => ({ name: link.name, url: link.url })) }); editing.value = true; }
function addLink(): void { form.links.push({ name: '', url: '' }); }
function removeLink(index: number): void { form.links.splice(index, 1); }
const validLink = (link: SolutionLink): boolean => Boolean(link.name.trim()) && /^https?:\/\//.test(link.url);
async function save(): Promise<void> { if (!form.title.trim() || !wrong.value) return; const updated = await wrongs.update(id, { title: form.title, category: form.category.trim(), difficulty: form.difficulty, review: form.review, solutionLinks: form.links.filter(validLink) }); if (updated) { wrong.value = updated; editing.value = false; } }
async function remove(): Promise<void> { if (window.confirm('确定删除这道错题吗？') && await wrongs.remove(id)) await router.push('/wrongs'); }
async function saveNotes(): Promise<void> { await store.replace(id, selected.value); }
async function unlink(noteId: string): Promise<void> { await store.remove(id, noteId); selected.value = selected.value.filter((item) => item !== noteId); }
onMounted(async () => { wrong.value = await wrongs.get(id); await Promise.all([store.fetch(id), store.fetchNotes()]); selected.value = store.notes.map((note) => note.id); });
</script>
<template><main class="grid gap-6 p-6 md:grid-cols-[1fr_300px]"><section><button class="mb-4 underline" @click="router.back">← 返回</button><p v-if="!wrong" role="status">正在加载错题…</p><template v-else><header class="border-b border-[var(--color-border)] pb-4"><div class="flex flex-wrap items-start justify-between gap-3"><div><h1 class="text-2xl font-semibold">{{ wrong.title }}</h1><p class="mt-2 text-sm text-[var(--color-accent)]">{{ labels[wrong.difficulty] }}<span v-if="wrong.category" class="ml-3">{{ wrong.category }}</span></p></div><div class="flex gap-3 text-sm"><button class="underline" @click="edit">编辑</button><button :disabled="wrongs.deleting" class="text-red-700 underline" @click="remove">删除</button></div></div></header><p v-if="wrongs.saveError" role="alert" class="mt-3 text-sm text-red-700">{{ wrongs.saveError }}</p><p v-if="wrongs.deleteError" role="alert" class="mt-3 text-sm text-red-700">{{ wrongs.deleteError }}</p>
<form v-if="editing" class="mt-5 space-y-4 border p-5" @submit.prevent="save"><h2 class="text-lg font-semibold">编辑错题</h2><label class="block">标题<input v-model="form.title" aria-label="错题标题" required maxlength="255" class="mt-1 w-full border px-3 py-2" /></label><label class="block">分类（自由文本）<input v-model="form.category" aria-label="错题分类" list="wrong-detail-category-presets" maxlength="100" class="mt-1 w-full border px-3 py-2" /><datalist id="wrong-detail-category-presets"><option v-for="preset in WRONG_CATEGORY_PRESETS" :key="preset" :value="preset" /></datalist></label><label class="block">难度<select v-model="form.difficulty" aria-label="错题难度" class="mt-1 w-full border px-3 py-2"><option value="EASY">简单</option><option value="MEDIUM">中等</option><option value="HARD">困难</option></select></label><label class="block">错因复盘<RichTextEditor v-model="form.review" class="mt-1" /></label><fieldset class="space-y-2"><legend class="font-semibold">题解链接</legend><div v-for="(link, index) in form.links" :key="index" class="flex flex-wrap gap-2"><input v-model="link.name" aria-label="链接名称" placeholder="名称" maxlength="100" class="min-w-0 flex-1 border px-3 py-2" /><input v-model="link.url" aria-label="链接地址" placeholder="https:// 开头" class="min-w-0 flex-1 border px-3 py-2" /><button type="button" class="text-red-700 underline" @click="removeLink(index)">移除</button></div><button type="button" class="border px-3 py-2 text-sm" @click="addLink">+ 添加链接</button><p class="text-xs opacity-60">保存时自动忽略名称为空或地址不是 http(s) 开头的行。</p></fieldset><div class="flex gap-3"><button :disabled="wrongs.saving" class="bg-[var(--color-accent)] px-4 py-2 text-white" type="submit">{{ wrongs.saving ? '保存中…' : '保存' }}</button><button type="button" class="border px-4 py-2" @click="editing = false">取消</button></div></form>
<div v-else class="mt-5 space-y-6"><article class="border p-5"><h2 class="font-semibold">错因复盘</h2><p v-if="!wrong.review" class="mt-3 text-sm opacity-60">暂无错因复盘，点「编辑」补充。</p><MarkdownRenderer v-else :content="wrong.review" class="mt-3" /></article><article class="border p-5"><h2 class="font-semibold">题解链接</h2><ul v-if="links.length" class="mt-3 space-y-2 text-sm"><li v-for="(link, index) in links" :key="index"><a :href="link.url" target="_blank" rel="noopener noreferrer" class="underline">{{ link.name }}</a></li></ul><p v-else class="mt-3 text-sm opacity-60">暂无题解链接。</p></article></div></template></section>
<aside class="space-y-5"><article class="border p-4"><h2 class="font-semibold">关联题解笔记</h2><ul class="mt-3 space-y-2 text-sm"><li v-for="note in store.notes" :key="note.id" class="flex items-center justify-between gap-2 border p-2"><RouterLink :to="`/notes/${note.id}`" class="min-w-0 truncate">{{ note.title }}</RouterLink><button class="shrink-0 text-red-700 underline" @click="unlink(note.id)">解除</button></li><li v-if="!store.notes.length" class="opacity-60">暂无关联笔记</li></ul></article><article class="border p-4"><h2 class="font-semibold">整体替换关联</h2><select v-model="selected" multiple aria-label="选择关联题解笔记" class="mt-3 w-full border p-2 text-sm"><option v-for="note in store.allNotes" :key="note.id" :value="note.id">{{ note.title }}</option></select><p v-if="store.error" role="alert" class="mt-2 text-sm text-red-700">{{ store.error }}</p><button class="mt-3 w-full border px-3 py-2 text-sm" @click="saveNotes">保存关联</button><p class="mt-2 text-xs opacity-60">按住 Ctrl/Cmd 可多选；保存将整体替换当前关联。</p></article></aside></main></template>
