<!-- Paginated wrong-problem list with server-side filters and creation. -->
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { useWrongListStore } from '../stores/wrongList';
import PaginationNav from '../components/PaginationNav.vue';
import { WRONG_CATEGORY_PRESETS } from '../constants';
import type { Difficulty } from '../types';
const store = useWrongListStore();
const difficultyLabel: Record<Difficulty, string> = { EASY: '简单', MEDIUM: '中等', HARD: '困难' };
const formOpen = ref(false); const form = ref({ title: '', category: '', difficulty: 'EASY' as Difficulty });
function openCreate(): void { form.value = { title: '', category: '', difficulty: 'EASY' }; formOpen.value = true; }
async function save(): Promise<void> { if (!form.value.title.trim()) return; const wrong = await store.create({ ...form.value }); if (wrong) formOpen.value = false; }
onMounted(() => store.fetch());
</script>
<template><section class="mx-auto max-w-5xl p-5 md:p-10"><header class="flex items-end justify-between border-b border-[var(--color-border)] pb-6"><div><p class="text-xs uppercase tracking-[0.18em] text-[var(--color-accent)]">Review desk / 01</p><h2 class="mt-2 text-3xl font-semibold tracking-tight">错题本</h2><p class="mt-2 max-w-xl text-sm opacity-70">把卡住你的题，整理成下一次能跨过去的台阶。</p></div><button class="shrink-0 bg-[var(--color-accent)] px-4 py-2 font-semibold text-white" @click="openCreate">新增错题</button></header><form class="mt-6 grid gap-3 border border-[var(--color-border)] bg-white/30 p-4 sm:grid-cols-[1fr_160px_130px_auto]" @submit.prevent="store.search"><label class="sr-only" for="wrong-keyword">搜索错题</label><input id="wrong-keyword" v-model="store.keyword" class="min-w-0 border border-[var(--color-border)] bg-transparent px-3 py-2" placeholder="搜索标题" /><input v-model="store.category" class="border border-[var(--color-border)] bg-transparent px-3 py-2" placeholder="分类（自由文本）" /><select v-model="store.difficulty" class="border border-[var(--color-border)] bg-transparent px-3 py-2"><option value="">全部难度</option><option value="EASY">简单</option><option value="MEDIUM">中等</option><option value="HARD">困难</option></select><button class="bg-[var(--color-accent)] px-4 py-2 font-semibold text-white" type="submit">筛选</button></form><p v-if="store.loading" class="py-12 text-center text-sm opacity-70">正在整理错题…</p><div v-else-if="store.error" class="mt-6 border border-red-300 p-5 text-sm text-red-700">{{ store.error }}<button class="ml-3 underline" @click="store.fetch">重试</button></div><div v-else-if="!store.items.length" class="mt-6 border border-dashed border-[var(--color-border)] p-10 text-center"><p class="font-semibold">这里还没有匹配的错题</p><p class="mt-2 text-sm opacity-70">调整筛选条件，或新增一条错题开始复盘。</p></div><div v-else class="mt-6 space-y-3"><RouterLink v-for="wrong in store.items" :key="wrong.id" :to="`/wrongs/${wrong.id}`" class="block border border-[var(--color-border)] p-4 transition-colors hover:border-[var(--color-accent)] hover:bg-[var(--color-accent-light)]/40"><div class="flex flex-wrap items-start justify-between gap-3"><h3 class="font-semibold">{{ wrong.title }}</h3><span class="border border-[var(--color-border)] px-2 py-1 text-xs">{{ difficultyLabel[wrong.difficulty] }}</span></div><div class="mt-4 flex flex-wrap gap-2 text-xs opacity-70"><span v-if="wrong.category">{{ wrong.category }}</span><span>{{ Array.isArray(wrong.solutionLinks) ? wrong.solutionLinks.length : 0 }} 个题解链接</span><span>{{ wrong.noteCount }} 篇关联笔记</span></div></RouterLink></div><PaginationNav class="mt-6" :page="store.pagination.page" :total-pages="store.pagination.totalPages" @page="store.setPage" />
<div v-if="formOpen" class="fixed inset-0 grid place-items-center bg-black/30 p-4"><form class="w-full max-w-md space-y-4 bg-[var(--color-bg)] p-5" @submit.prevent="save"><h3 class="text-xl font-semibold">新增错题</h3><label class="block">错题标题<input v-model="form.title" aria-label="错题标题" required maxlength="255" class="mt-1 w-full border px-3 py-2" /></label><label class="block">分类（自由文本）<input v-model="form.category" aria-label="错题分类" list="wrong-category-presets" maxlength="100" class="mt-1 w-full border px-3 py-2" /><datalist id="wrong-category-presets"><option v-for="preset in WRONG_CATEGORY_PRESETS" :key="preset" :value="preset" /></datalist></label><label class="block">难度<select v-model="form.difficulty" aria-label="错题难度" class="mt-1 w-full border px-3 py-2"><option value="EASY">简单</option><option value="MEDIUM">中等</option><option value="HARD">困难</option></select></label><p v-if="store.saveError" role="alert" class="text-sm text-red-700">{{ store.saveError }}</p><div class="flex justify-end gap-3"><button type="button" class="border px-4 py-2" @click="formOpen = false">取消</button><button :disabled="store.saving" class="bg-[var(--color-accent)] px-4 py-2 text-white" type="submit">{{ store.saving ? '保存中…' : '保存' }}</button></div></form></div></section></template>
