// 处理分类模块 HTTP 请求并统一转交错误中间件。
import { NextFunction, Request, Response } from 'express';
import { isCategoryIdsInput, isCategoryInput, parseCategoryQuery } from './category.dto';
import * as service from './category.service';

const handle = (error: unknown, next: NextFunction): void => { if (error instanceof service.CategoryError) { next(error); return; } next(error); };
const param = (req: Request, name: string): string => { const value = req.params[name]; if (!value || Array.isArray(value)) throw new service.CategoryError('VALIDATION_ERROR', 'Invalid route parameter', 400); return value; };
export const getCategories = async (req: Request, res: Response, next: NextFunction): Promise<void> => { try { res.json(await service.listCategories(req.auth!.sub, parseCategoryQuery(req.query))); } catch (error: unknown) { handle(error, next); } };
export const postCategory = async (req: Request, res: Response, next: NextFunction): Promise<void> => { try { if (!isCategoryInput(req.body)) throw new service.CategoryError('VALIDATION_ERROR', 'Invalid category payload', 400); res.status(201).json(await service.createCategory(req.auth!.sub, req.body)); } catch (error: unknown) { handle(error, next); } };
export const patchCategory = async (req: Request, res: Response, next: NextFunction): Promise<void> => { try { if (!isCategoryInput(req.body)) throw new service.CategoryError('VALIDATION_ERROR', 'Invalid category payload', 400); res.json(await service.renameCategory(req.auth!.sub, param(req, 'categoryId'), req.body)); } catch (error: unknown) { handle(error, next); } };
export const removeCategory = async (req: Request, res: Response, next: NextFunction): Promise<void> => { try { await service.deleteCategory(req.auth!.sub, param(req, 'categoryId')); res.status(204).send(); } catch (error: unknown) { handle(error, next); } };
export const getCategoryProblems = async (req: Request, res: Response, next: NextFunction): Promise<void> => { try { const page = Math.max(1, Number(req.query.page) || 1); const pageSize = Math.min(100, Math.max(1, Number(req.query.pageSize) || 20)); res.json(await service.listCategoryProblems(req.auth!.sub, param(req, 'categoryId'), page, pageSize, typeof req.query.keyword === 'string' ? req.query.keyword.trim() : undefined, typeof req.query.difficulty === 'string' ? req.query.difficulty : undefined)); } catch (error: unknown) { handle(error, next); } };
export const putProblemCategories = async (req: Request, res: Response, next: NextFunction): Promise<void> => { try { if (!isCategoryIdsInput(req.body)) throw new service.CategoryError('INVALID_CATEGORY_IDS', 'Category IDs are invalid', 400); res.json(await service.replaceProblemCategories(req.auth!.sub, param(req, 'problemId'), req.body)); } catch (error: unknown) { handle(error, next); } };
