// 处理分类模块 HTTP 请求并统一转交错误中间件。
import { NextFunction, Request, Response } from 'express';
import { isCategoryIdsInput, isCategoryInput, parseCategoryQuery } from './category.dto';
import * as service from './category.service';
import { ApiError, parseIdParam } from '../../lib/errors';
export const getCategories = async (req: Request, res: Response, next: NextFunction): Promise<void> => { try { res.json(await service.listCategories(req.auth!.sub, parseCategoryQuery(req.query))); } catch (error: unknown) { next(error); } };
export const postCategory = async (req: Request, res: Response, next: NextFunction): Promise<void> => { try { if (!isCategoryInput(req.body)) throw new ApiError(400, 'VALIDATION_ERROR', 'Invalid category payload'); res.status(201).json(await service.createCategory(req.auth!.sub, req.body)); } catch (error: unknown) { next(error); } };
export const patchCategory = async (req: Request, res: Response, next: NextFunction): Promise<void> => { try { if (!isCategoryInput(req.body)) throw new ApiError(400, 'VALIDATION_ERROR', 'Invalid category payload'); res.json(await service.renameCategory(req.auth!.sub, parseIdParam(req, 'categoryId'), req.body)); } catch (error: unknown) { next(error); } };
export const removeCategory = async (req: Request, res: Response, next: NextFunction): Promise<void> => { try { await service.deleteCategory(req.auth!.sub, parseIdParam(req, 'categoryId')); res.status(204).send(); } catch (error: unknown) { next(error); } };
export const getCategoryProblems = async (req: Request, res: Response, next: NextFunction): Promise<void> => { try { const page = Math.max(1, Number(req.query.page) || 1); const pageSize = Math.min(100, Math.max(1, Number(req.query.pageSize) || 20)); res.json(await service.listCategoryProblems(req.auth!.sub, parseIdParam(req, 'categoryId'), page, pageSize, typeof req.query.keyword === 'string' ? req.query.keyword.trim() : undefined, typeof req.query.difficulty === 'string' ? req.query.difficulty : undefined)); } catch (error: unknown) { next(error); } };
export const putProblemCategories = async (req: Request, res: Response, next: NextFunction): Promise<void> => { try { if (!isCategoryIdsInput(req.body)) throw new ApiError(400, 'INVALID_CATEGORY_IDS', 'Category IDs are invalid'); res.json(await service.replaceProblemCategories(req.auth!.sub, parseIdParam(req, 'problemId'), req.body)); } catch (error: unknown) { next(error); } };
