// 实现待办的查询、创建、编辑与删除业务。
import { Prisma, TodoPriority, TodoStatus } from '@prisma/client';
import { prisma } from '../../config/prisma';
import { TodoInput, TodoPatch, TodoQuery } from './todo.dto';
export class TodoError extends Error { public constructor(public readonly code: string, message: string, public readonly statusCode: number) { super(message); } }
const select = { id: true, title: true, dueDate: true, priority: true, status: true, remark: true, createdAt: true, updatedAt: true } as const;
const today = (): Date => { const value = new Date(); return new Date(Date.UTC(value.getFullYear(), value.getMonth(), value.getDate())); };
const convert = (row: Prisma.TodoGetPayload<{ select: typeof select }>) => ({ ...row, isOverdue: row.dueDate !== null && row.status !== TodoStatus.COMPLETED && row.dueDate < today() });
const missing = (error: unknown): never => { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2025') throw new TodoError('TODO_NOT_FOUND', 'Todo does not exist', 404); throw error; };
export const listTodos = async (userId: string, query: TodoQuery) => { const where: Prisma.TodoWhereInput = { userId, ...(query.status ? { status: query.status } : {}), ...(query.priority ? { priority: query.priority } : {}), ...(query.keyword ? { OR: [{ title: { contains: query.keyword, mode: 'insensitive' } }, { remark: { contains: query.keyword, mode: 'insensitive' } }] } : {}), ...(query.overdue ? { status: { not: TodoStatus.COMPLETED }, dueDate: { lt: today() } } : {}) }; const [total, rows] = await prisma.$transaction([prisma.todo.count({ where }), prisma.todo.findMany({ where, select, orderBy: [{ status: 'asc' }, { dueDate: { sort: 'asc', nulls: 'last' } }, { priority: 'asc' }, { createdAt: 'desc' }], skip: (query.page - 1) * query.pageSize, take: query.pageSize })]); return { data: rows.map(convert), pagination: { page: query.page, pageSize: query.pageSize, total, totalPages: Math.ceil(total / query.pageSize) } }; };
export const getTodo = async (userId: string, id: string) => { const row = await prisma.todo.findFirst({ where: { id, userId }, select }); if (!row) throw new TodoError('TODO_NOT_FOUND', 'Todo does not exist', 404); return { data: convert(row) }; };
const dateValue = (value: string | null | undefined): Date | null | undefined => value === undefined ? undefined : value === null ? null : new Date(`${value}T00:00:00.000Z`);
export const createTodo = async (userId: string, input: TodoInput) => ({ data: convert(await prisma.todo.create({ data: { userId, title: input.title.trim(), dueDate: dateValue(input.dueDate), priority: input.priority, status: input.status ?? TodoStatus.TODO, remark: input.remark ?? null }, select })) });
export const updateTodo = async (userId: string, id: string, input: TodoPatch) => { try { return { data: convert(await prisma.todo.update({ where: { id, userId }, data: { ...(input.title === undefined ? {} : { title: input.title.trim() }), ...(input.dueDate === undefined ? {} : { dueDate: dateValue(input.dueDate) }), ...(input.priority === undefined ? {} : { priority: input.priority }), ...(input.status === undefined ? {} : { status: input.status }), ...(input.remark === undefined ? {} : { remark: input.remark }) }, select })) }; } catch (error: unknown) { return missing(error); } };
export const deleteTodo = async (userId: string, id: string): Promise<void> => { try { await prisma.todo.delete({ where: { id, userId } }); } catch (error: unknown) { missing(error); } };
